import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    files: ['src/database/index.js'],
    rules: {
      'no-sync': 'off',
    },
  },
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        // Node.js globals
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        // ES2021 globals
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        queueMicrotask: 'readonly',
        fetch: 'readonly',
      },
    },
    rules: {
      // === FIXABLE RULES - Maximum Auto-Fixing ===

      // Possible Errors (all fixable)
      'no-extra-parens': ['warn', 'all', { conditionalAssign: false, nestedBinaryExpressions: false }],
      'no-extra-semi': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-regex-spaces': 'error',
      'no-unexpected-multiline': 'error',
      'valid-typeof': ['error', { requireStringLiterals: true }],

      // Best Practices (mostly fixable)
      'array-callback-return': ['warn', { allowImplicit: false, checkForEach: true }],
      'block-scoped-var': 'error',
      'consistent-return': 'warn',
      'curly': ['error', 'all'],
      'default-case': 'warn',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-notation': ['error', { allowKeywords: true }],
      'eqeqeq': ['warn', 'always', { null: 'ignore' }],
      'no-alert': 'warn',
      'no-array-constructor': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['error', 'always'],
      'no-const-assign': 'error',
      'no-constant-condition': 'warn',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': ['warn', { allowEmptyCatch: false }],
      'no-empty-character-class': 'error',
      'no-empty-function': ['warn', { allow: [] }],
      'no-empty-pattern': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': ['error', { commentPattern: 'falls?through' }],
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': ['error', 'both'],
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'error',
      'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'warn',
      'no-mixed-requires': ['warn', { grouping: true }],
      'no-multi-assign': 'warn',
      'no-multi-str': 'error',
      'no-negated-condition': 'warn',
      'no-nested-ternary': 'warn',
      'no-new': 'warn',
      'no-new-func': 'error',
      'no-new-object': 'error',
      'no-new-wrappers': 'error',
      'no-obj-calls': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': ['warn', { props: false }],
      'no-plusplus': 'off',
      'no-proto': 'error',
      'no-prototype-builtins': 'warn',
      'no-redeclare': ['error', { builtinGlobals: true }],
      'no-return-assign': ['error', 'always'],
      'no-return-await': 'warn',
      'no-script-url': 'error',
      'no-self-assign': ['error', { props: true }],
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': 'off',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'warn',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-unreachable': 'warn',
      'no-unreachable-loop': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unused-expressions': ['warn', { allowShortCircuit: true, allowTernary: true }],
      'no-unused-labels': 'error',
      'no-unused-vars': ['warn', { vars: 'all', args: 'after-used', ignoreRestSiblings: true, argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-use-before-define': ['warn', { functions: false, classes: true, variables: true }],
      'no-useless-catch': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-escape': 'error',
      'no-useless-rename': ['error', { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false }],
      'no-useless-return': 'warn',
      'no-var': 'error',
      'no-void': 'warn',
      'no-with': 'error',
      'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
      'prefer-destructuring': ['warn', { array: false, object: true }, { enforceForRenamedProperties: false }],
      'prefer-exponentiation-operator': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': ['warn', { disallowRedundantWrapping: true }],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'radix': ['error', 'as-needed'],
      'require-await': 'warn',
      'require-unicode-regexp': 'off',
      'require-yield': 'error',
      'vars-on-top': 'error',
      'yoda': ['error', 'never', { onlyEquality: false }],

      // Variables (fixable)
      'no-catch-shadow': 'error',
      'no-label-var': 'error',
      'no-shadow-restricted-names': 'error',
      'no-undefined': 'warn',

      // Node.js (fixable)
      'no-buffer-constructor': 'error',
      'no-new-require': 'error',
      'no-path-concat': 'error',
      'no-process-env': 'off',
      'no-process-exit': 'warn',
      'no-sync': 'warn',

      // Stylistic Issues (all fixable - maximum auto-refactoring)
      'array-bracket-spacing': ['error', 'never'],
      'array-element-newline': ['warn', 'consistent'],
      'arrow-body-style': ['error', 'as-needed', { requireReturnForObjectLiteral: false }],
      'arrow-parens': ['error', 'always'],
      'arrow-spacing': ['error', { before: true, after: true }],
      'block-spacing': ['error', 'always'],
      'brace-style': ['error', '1tbs', { allowSingleLine: true }],
      'camelcase': ['warn', { properties: 'always', ignoreDestructuring: false, ignoreImports: true }],
      'capitalized-comments': 'off',
      'comma-dangle': ['error', 'always-multiline'],
      'comma-spacing': ['error', { before: false, after: true }],
      'comma-style': ['error', 'last'],
      'computed-property-spacing': ['error', 'never'],
      'consistent-this': 'off',
      'eol-last': ['error', 'always'],
      'func-call-spacing': ['error', 'never'],
      'func-name-matching': ['warn', 'always', { includeCommonJSModuleExports: true }],
      'func-names': ['warn', 'as-needed'],
      'func-style': ['warn', 'declaration', { allowArrowFunctions: true }],
      'function-call-argument-newline': ['warn', 'consistent'],
      'function-paren-newline': ['warn', 'consistent'],
      'id-denylist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'implicit-arrow-linebreak': ['error', 'beside'],
      'indent': ['error', 2, { SwitchCase: 1, VariableDeclarator: 'first', MemberExpression: 1 }],
      'jsx-quotes': 'off',
      'key-spacing': ['error', { beforeColon: false, afterColon: true, mode: 'strict' }],
      'keyword-spacing': ['error', { before: true, after: true }],
      'line-comment-position': 'off',
      'linebreak-style': ['error', 'unix'],
      'lines-around-comment': 'off',
      'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
      'max-depth': 'off',
      'max-len': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-nested-callbacks': 'off',
      'max-params': 'off',
      'max-statements': 'off',
      'max-statements-per-line': 'off',
      'multiline-comment-style': 'off',
      'multiline-ternary': ['warn', 'always-multiline'],
      'new-cap': ['warn', { newIsCap: true, capIsNew: false, properties: false }],
      'new-parens': 'error',
      'newline-after-var': 'off',
      'newline-before-return': 'off',
      'newline-per-chained-call': 'off',
      'no-bitwise': 'warn',
      'no-inline-comments': 'off',
      'no-lonely-if': 'error',
      'no-mixed-operators': 'off',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multi-assign': 'warn',
      'no-multi-spaces': 'error',
      'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1, maxBOF: 0 }],
      'no-negated-condition': 'warn',
      'no-nested-ternary': 'warn',
      'no-tabs': 'error',
      'no-trailing-spaces': 'error',
      'no-unneeded-ternary': ['error', { defaultAssignment: false }],
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': ['error', 'beside'],
      'object-curly-newline': ['error', { multiline: true, consistent: true }],
      'object-curly-spacing': ['error', 'always'],
      'object-property-newline': ['error', { allowMultiplePropertiesPerLine: true }],
      'one-var': ['error', 'never'],
      'one-var-declaration-per-line': ['error', 'always'],
      'operator-assignment': ['error', 'always'],
      'operator-linebreak': ['error', 'before', { overrides: { '=': 'none', '&&': 'before', '||': 'before', '??': 'before' } }],
      'padded-blocks': ['error', 'never'],
      'padding-line-between-statements': 'off',
      'prefer-exponentiation-operator': 'error',
      'prefer-object-spread': 'error',
      'quote-props': ['warn', 'as-needed', { keywords: false, unnecessary: true, numbers: false }],
      'quotes': ['error', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
      'semi': ['error', 'always'],
      'semi-spacing': ['error', { before: false, after: true }],
      'semi-style': ['error', 'last'],
      'sort-keys': 'off',
      'sort-vars': 'off',
      'space-before-blocks': ['error', 'always'],
      'space-before-function-paren': ['error', { anonymous: 'always', named: 'never', asyncArrow: 'always' }],
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'error',
      'space-unary-ops': ['error', { words: true, nonwords: false }],
      'spaced-comment': ['warn', 'always', { markers: ['/'], exceptions: ['-', '+'] }],
      'switch-colon-spacing': ['error', { after: true, before: false }],
      'template-curly-spacing': ['error', 'never'],
      'template-tag-spacing': ['error', 'never'],
      'unicode-bom': ['error', 'never'],
      'wrap-iife': ['error', 'any', { functionPrototypeMethods: false }],
      'wrap-regex': 'off',
      'yield-star-spacing': ['error', 'both'],

      // ES6 (fixable - maximum auto-refactoring)
      'constructor-super': 'error',
      'generator-star-spacing': ['error', { before: true, after: false }],
      'no-confusing-arrow': ['error', { allowParens: true }],
      'no-const-assign': 'error',
      'no-dupe-class-members': 'error',
      'no-duplicate-imports': 'error',
      'no-new-symbol': 'error',
      'no-restricted-exports': 'off',
      'no-restricted-imports': 'off',
      'no-this-before-super': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': ['error', { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false }],
      'no-var': 'error',
      'object-shorthand': ['error', 'always', { avoidQuotes: true, ignoreConstructors: false, avoidExplicitReturnArrows: true }],
      'prefer-arrow-callback': ['error', { allowNamedFunctions: false, allowUnboundThis: true }],
      'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
      'prefer-destructuring': ['warn', { array: false, object: true }, { enforceForRenamedProperties: false }],
      'prefer-exponentiation-operator': 'error',
      'prefer-named-capture-group': 'off',
      'prefer-numeric-literals': 'error',
      'prefer-object-has-own': 'warn',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': ['warn', { disallowRedundantWrapping: true }],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'require-yield': 'error',
      'rest-spread-spacing': ['error', 'never'],
      'sort-imports': ['warn', { ignoreCase: false, ignoreDeclarationSort: true, ignoreMemberSort: false, memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'] }],
      'symbol-description': 'warn',
      'template-curly-spacing': ['error', 'never'],
      'yield-star-spacing': ['error', 'both'],
    },
  },
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'build/**',
      '.git/**',
      'coverage/**',
      '*.config.js',
      'eslint.config.js',
    ],
  },
];
